# Stage 1
FROM node:16-alpine as build
WORKDIR /client
COPY package*.json ./
# Installing packages
RUN yarn --silent
COPY . .
# Start development server
RUN yarn build --silent

# Stage 2
FROM nginx:1.21.0-alpine
COPY --from=build /client/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]