version: "3.7"
services:
    frontend:
        container_name: Client
        image: dreed657/rockypodsclient
        build:
            context: ./Client
            dockerfile: ./Dockerfile
        ports:
            - "3000:3000"

    backend:
        container_name: Server
        image: dreed657/rockypodsserver
        build:
            context: ./Server
            dockerfile: ./Dockerfile
        ports:
            - "5000:5000"