version: "3.7"
services:
  frontend:
    build:
      context: ./Client
      dockerfile: ./Dockerfile.Prod
    ports:
      - "80:80"

  backend:
    build:
      context: ./Server
      dockerfile: ./Dockerfile.Prod
