version: "3.7"
services:
    frontend:
        container_name: Client
        image: dreed657/rockypodsclient
        build:
            context: ./Client
            dockerfile: ./Dockerfile.Prod
        ports:
            - "3000:3000"
        networks: 
            - rocky-network
            
    backend:
        container_name: Server
        image: dreed657/rockypodsserver
        build:
            context: ./Server
            dockerfile: ./Dockerfile.Prod
        ports:
            - "5000:5000"
        networks: 
            - rocky-network

    mongodb:
        image: mongo
        container_name: mongodb
        ports:
            - 12500:27017
        restart: unless-stopped
        networks: 
            - rocky-network

networks:
    rocky-network: