version: "3.7"
services:
    frontend:
        container_name: Client
        build:
            context: ./Client
            dockerfile: ./Dockerfile.Dev
        ports:
            - "80:3000"
        networks: 
            - rocky-network

    dashboard:
        container_name: Dashboard
        build:
            context: ./dashboard
            dockerfile: ./Dockerfile.Dev
        ports:
            - "3000:3000"
        networks: 
            - rocky-network
            
    backend:
        container_name: Server
        build:
            context: ./Server
            dockerfile: ./Dockerfile.Dev
        ports:
            - "5000:5000"
        networks: 
            - rocky-network

networks:
    rocky-network: